### ISSUE TITLE
pb_download command...

### ISSUE THREAD

**Issue by dblodgett-usgs** [mdsumner/rasterwise#3]
```r
pb_download("weird.tar.gz", dest = ".", repo = "mdsumner/rasterwise", tag = "v0.0.11")
untar("weird.tar.gz")
``` 

worked for me. Note that the README is a bit out of date.

**Comment by mdsumner** [comment]
Ah thanks! Actually I wonder if changing the version is ever a good idea, I might set it and keep adding. It's not too big yet

**Comment by mdsumner** [comment]
I left a note to remind me of what to do ;)
